from enum import Enum

# Contiene todos los tokens que se requieren con sus valores
class TokenType(Enum):
    ENDFILE = 300
    ERROR = 301

    # Reserved words
    KALTXI = 'kaltxì' # hello
    RUTXE = 'rutxe'  # please
    IRAYO = 'irayo' # thanks
    EWLL = 'ewll' # plant
    EYLAN = 'eylan' # friend
    IPU = 'ipu' # humorous
    RRTA = 'Rrta' # Earth
    ATAN = 'atan' # light
    ATXKXE = 'atxkxe' # land
    AHO = 'aho' # pray
    EAMPIN = 'eampin' # blue | green
    EMREY= 'emrey' # survive
    EYAWR= 'eyawr' # correct
    EYKTAN = 'eyktan' # leader
    EYWA = 'Eywa'
    PANDORA = 'Pandora'
    FAHEW = 'fahew' # smell
    TAWTUTE = 'tawtute' # sky-person
    FEKUM = 'fekum' # disadvantage
    FRAPO = 'frapo' # everyone
    FENGE = 'fenge' # mock
    FRAW = 'fraw' # everything
    FRRFEN = 'frrfen' #visit
    FRRTU = 'frrtu' # guest
    FTIA = 'ftia' # study
    FTUE = 'ftue' # easy
    FITRR = 'fìtrr' # today
    FKAY = 'fkay' # hateful
    FKXEN = 'fkxen' # vegetable
    FLEL = 'flel' # fool (someone)
    FTXAVANG = 'ftxavang' # passionate
    FTXILOR = 'ftxìlor' # delicious
    FWEL = 'fwel' # whistle
    FWING = 'fwìng' # humiliation
    FMOKX = 'fmokx' # jealosy
    FPEIO = 'fpeio' # challenge
    HAHAW = 'hahaw' # sleep
    HAWAY = 'haway' # lullaby
    HWAMPAM = 'hwampam' # noise
    HOAN = 'hoan' # comfort
    HONA = 'hona' # adorable
    HENA = 'hena' # carry
    HUPX = 'hupx' # miss, not hit a target
    HURU = 'huru' # cooking pot
    HERWI = 'herwì' # snow
    IOANG = 'ioang' # animal/ beast
    KAKAN = 'kakan' # rought behaviour
    KAKREL = 'kakrel' # blind
    KERUSEY = 'kerusey' # dead
    KESRAN = 'kesran' # mediocre
    KETRIP = 'ketrìp' # Outcast
    KETSTUN = 'ketstun' # unkind 
    KANU = 'kanu' # intelligent
    KEWONG = 'kewong' # alien
    KEWAN = 'kewan' # age
    KEY = 'key' # face
    KEYWAR = 'keywar' # incorrect
    KILVAN = 'kilvan' #river
    KARYU = 'karyu' #teacher
    KATIR = 'katir' # rainbown
    KAWKRR = 'kawkrr' #never
    KAWNGTUN = 'kawngtun' # evil person
    KEFPOMTOKXNGA = 'kefpomtokxnga' # unhealthful
    KELKU = 'kelku' # home
    KOSMAN = 'kosman' # wonderful"
    KELTSUN = 'keltsun' #impossible
    KEMUIA = 'kemuia' # dishonor
    KEMUM = 'kemum' # IDK
    KXUTU = 'kxutu' # enemy
    LAFYON = 'lafyon' # wise
    LAWR = 'lawr' # melody
    MOKRI = 'mokri' # voice
    MAWUPTSYYIP = 'mawuptsyìp' # turtle
    NIM = 'nim' # shy
    NUME = 'nume' # learn
    NGEYN = 'ngeyn' # tired
    OARE = 'oare' # moon
    ONLOR = 'onlor' # good-smelling
    PAMTESEO = 'pamteseo' # music
    PARUL = 'parul' # miracle
    PASUK = 'pasuk' # berry
    PIWOPX = 'pìwopx' # cloud
    POM = 'pom' #kiss
    PRRNEN = 'prrnen' # baby | infant
    PXANOPIN = 'pxanopin' #colorful
    RAWMPXOM = 'rawmpxom' # thunder
    REWOM = 'rewom' # morning
    REY = 'rey' # live
    REPAY = 'repay' # blood
    RIM = 'rim' # yellow
    SNGEL = 'sngel' # garbage
    SOP = 'sop' # travel
    SOPYU = 'sopyu' # traveller
    SPAW = 'spaw' # believe
    SPONO = 'spono' # island
    SREW = 'srew' # dance
    SRUNG = 'srung' # help
    SAY = 'say' # loyal
    STXELI = 'stxeli' # gift
    SAYRIP = 'sayrìp' # handsome
    SEMPUL = 'sempul' # father
    SEVIN = 'sevin' # pretty
    SUR = 'sur' # taste
    SWEY = 'swey' # best
    SLELE = 'slele' # swim
    TINAWRI = 'tìnawri' # talent
    TINOMUN = 'tìnomum' # curiosity
    TARONYU = 'taronyu' # hunter
    TAUTRAL = 'tautral' # sky tree
    ZEYKOYU = 'zeykoyu' # healer
    YAFKEYK = 'yafkeyk' # weather
    YEWLA = 'yewla' # disappointment


    # Multicharacter tokens
    ID = 310
    NUM = 311
    STRING = 312

    # Special Symbols
    ASSIGN = ':='
    PLUS = '+'
    MINUS = '-'
    LPAREN = '('
    RPAREN = ')'
    SEMI = ';'
    COMMA = ','
    PERCENT = '%'
    DOT = '.'
    QUOTE = "'"
    TILDE = '~' 
    AMPERSAND = '&'
    EXCLAMATION ='!'
    LT = '<'
    RT = '>'
    TIMES = '*'
    
# StateType
class StateType(Enum):
    START = 0
    INASSIGN = 1
    INCOMMENT = 2
    INNUM = 3
    INID = 4
    DONE = 5

class ReservedWords(Enum):
    KALTXI = 'kaltxì' # hello
    RUTXE = 'rutxe'  # please
    IRAYO = 'irayo' # thanks
    EWLL = 'ewll' # plant
    EYLAN = 'eylan' # friend
    IPU = 'ipu' # humorous
    RRTA = 'Rrta' # Earth
    ATAN = 'atan' # light
    ATXKXE = 'atxkxe' # land
    AHO = 'aho' # pray
    EAMPIN = 'eampin' # blue | green
    EMREY= 'emrey' # survive
    EYAWR= 'eyawr' # correct
    EYKTAN = 'eyktan' # leader
    EYWA = 'Eywa'
    PANDORA = 'Pandora'
    FAHEW = 'fahew' # smell
    TAWTUTE = 'tawtute' # sky-person
    FEKUM = 'fekum' # disadvantage
    FRAPO = 'frapo' # everyone
    FENGE = 'fenge' # mock
    FRAW = 'fraw' # everything
    FRRFEN = 'frrfen' #visit
    FRRTU = 'frrtu' # guest
    FTIA = 'ftia' # study
    FTUE = 'ftue' # easy
    FITRR = 'fìtrr' # today
    FKAY = 'fkay' # hateful
    FKXEN = 'fkxen' # vegetable
    FLEL = 'flel' # fool (someone)
    FTXAVANG = 'ftxavang' # passionate
    FTXILOR = 'ftxìlor' # delicious
    FWEL = 'fwel' # whistle
    FWING = 'fwìng' # humiliation
    FMOKX = 'fmokx' # jealosy
    FPEIO = 'fpeio' # challenge
    HAHAW = 'hahaw' # sleep
    HAWAY = 'haway' # lullaby
    HWAMPAM = 'hwampam' # noise
    HOAN = 'hoan' # comfort
    HONA = 'hona' # adorable
    HENA = 'hena' # carry
    HUPX = 'hupx' # miss, not hit a target
    HURU = 'huru' # cooking pot
    HERWI = 'herwì' # snow
    IOANG = 'ioang' # animal/ beast
    KAKAN = 'kakan' # rought behaviour
    KAKREL = 'kakrel' # blind
    KERUSEY = 'kerusey' # dead
    KESRAN = 'kesran' # mediocre
    KETRIP = 'ketrìp' # Outcast
    KETSTUN = 'ketstun' # unkind 
    KANU = 'kanu' # intelligent
    KEWONG = 'kewong' # alien
    KEWAN = 'kewan' # age
    KEY = 'key' # face
    KEYWAR = 'keywar' # incorrect
    KILVAN = 'kilvan' #river
    KARYU = 'karyu' #teacher
    KATIR = 'katir' # rainbown
    KAWKRR = 'kawkrr' #never
    KAWNGTUN = 'kawngtun' # evil person
    KEFPOMTOKXNGA = 'kefpomtokxnga' # unhealthful
    KELKU = 'kelku' # home
    KOSMAN = 'kosman' # wonderful"
    KELTSUN = 'keltsun' #impossible
    KEMUIA = 'kemuia' # dishonor
    KEMUM = 'kemum' # IDK
    KXUTU = 'kxutu' # enemy
    LAFYON = 'lafyon' # wise
    LAWR = 'lawr' # melody
    MOKRI = 'mokri' # voice
    MAWUPTSYYIP = 'mawuptsyìp' # turtle
    NIM = 'nim' # shy
    NUME = 'nume' # learn
    NGEYN = 'ngeyn' # tired
    OARE = 'oare' # moon
    ONLOR = 'onlor' # good-smelling
    PAMTESEO = 'pamteseo' # music
    PARUL = 'parul' # miracle
    PASUK = 'pasuk' # berry
    PIWOPX = 'pìwopx' # cloud
    POM = 'pom' #kiss
    PRRNEN = 'prrnen' # baby | infant
    PXANOPIN = 'pxanopin' #colorful
    RAWMPXOM = 'rawmpxom' # thunder
    REWOM = 'rewom' # morning
    REY = 'rey' # live
    REPAY = 'repay' # blood
    RIM = 'rim' # yellow
    SNGEL = 'sngel' # garbage
    SOP = 'sop' # travel
    SOPYU = 'sopyu' # traveller
    SPAW = 'spaw' # believe
    SPONO = 'spono' # island
    SREW = 'srew' # dance
    SRUNG = 'srung' # help
    SAY = 'say' # loyal
    STXELI = 'stxeli' # gift
    SAYRIP = 'sayrìp' # handsome
    SEMPUL = 'sempul' # father
    SEVIN = 'sevin' # pretty
    SUR = 'sur' # taste
    SWEY = 'swey' # best
    SLELE = 'slele' # swim
    TINAWRI = 'tìnawri' # talent
    TINOMUN = 'tìnomum' # curiosity
    TARONYU = 'taronyu' # hunter
    TAUTRAL = 'tautral' # sky tree
    ZEYKOYU = 'zeykoyu' # healer
    YAFKEYK = 'yafkeyk' # weather
    YEWLA = 'yewla' # disappointment
